config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  validates :name, presence: true
  validates :email, presence: true,
                    uniqueness: {case_sensitive: false}
  validates :password, presence: true
  before_save :downcase_email
  has_secure_password

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(string)
    Digest::SHA1.hexdigest(string)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    User.digest(token) == send("#{attribute}_digest")
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  private

      # Converts email to all lower-case.
      def downcase_email
        self.email = email.downcase
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :redirect_guest, only: [:new,:create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Post successfully submitted."
      redirect_to root_url
    else
      redirect_to root_url
    end
  end

  def index
    @posts = Post.all
  end

  private

    def post_params
      params.require(:post).permit(:body, :user_id)
    end

    def redirect_guest
      redirect_to sign_in_path unless logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      redirect_to root_url
    else
      flash.now[:danger] = "Invalid email/password combination."
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:id)
    cookies.delete(:remember_token)
  end
end

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="container">
    <%= link_to "Members Only", root_path %>
    <% if logged_in? %>
      <%= link_to "Create new post", new_post_path %>
      <%= link_to "Log out", logout_path, method: :delete %>
    <% else %>
      <li><%= link_to "Log In", login_path %></li>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<br>
<% @posts.each do |post| %>
  <%= content_tag(:p, post.body) %>
  <% if logged_in? %>
    <%= content_tag(:p, '') do %>
      <%= "#{distance_of_time_in_words(post.created_at, Time.zone.now)} ago by #{post.user.name}" %>
    <% end %><br>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%= form_for(@post) do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.text_area :body %><br>
  <%= f.submit "Submit" %>
<% end %>